/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import constant.SpecialityConstant;
import constant.WorkplaceConstant;
import entity.Clazz;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.Main;

/**
 *
 * @author Admin
 */
public class ClazzMangementFrame extends javax.swing.JFrame {

    /**
     * Creates new form LecturerMangementFrame
     */
    private ArrayList<Clazz> clazzes = new ArrayList<>();
    private String workplace;
    
    public ClazzMangementFrame(ArrayList<Clazz> clazzes, String workplace){
        this.workplace = workplace;
        for (Clazz clazz : main.Main.clazzes) {
            if (WorkplaceConstant.DICHVONGHAU.equals(workplace)){
                this.clazzes.add(clazz);
            }
        }
        displayJTable();
    }
    public ClazzMangementFrame() {
        initComponents();
        for (Clazz clazz : Main.clazzes) {
            Vector vectorRow = new Vector();
            vectorRow.add(clazz.getId());
            if (clazz.getLecturer() == null){
//                vectorRow.add("");
                vectorRow.add(clazz.getLecturerName());
            } else {
                vectorRow.add(clazz.getLecturer().getName());
            }
            vectorRow.add(clazz.getSpeciality());
            vectorRow.add(clazz.getName());
            vectorRow.add(clazz.getSchedule());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSchedule = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblClassName = new javax.swing.JLabel();
        lblSchedule = new javax.swing.JLabel();
        rdEv = new javax.swing.JRadioButton();
        rdOdd = new javax.swing.JRadioButton();
        cboSpeciality = new javax.swing.JComboBox<>();
        txtClassName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        txtLecturerName = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPreference = new javax.swing.JMenuItem();
        menuSecurity = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CLass's Id", "Lecturer's Name", "Speciality", "Class's Name", "Schedule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblName.setText("Lecturer's Name:");

        lblSpeciality.setText("Speciality:");

        lblClassName.setText("Class's Name:");

        lblSchedule.setText("Schedule:");

        btnGroupSchedule.add(rdEv);
        rdEv.setText("Mon, Wed, Fri ");
        rdEv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEvActionPerformed(evt);
            }
        });

        btnGroupSchedule.add(rdOdd);
        rdOdd.setText("Tue, Thur, Sat");
        rdOdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOddActionPerformed(evt);
            }
        });

        cboSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WEB BACK-END", "WEB FRONT-END", "DEVOPS & AWS", "MOBILE", "STEM" }));
        cboSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSpecialityActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnFilter.setText("Filter");

        jMenu1.setText("Setting");
        jMenu1.setToolTipText("");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuPreference.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPreference.setText("Security");
        menuPreference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreferenceActionPerformed(evt);
            }
        });
        jMenu1.add(menuPreference);

        menuSecurity.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSecurity.setText("Preference");
        menuSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecurityActionPerformed(evt);
            }
        });
        jMenu1.add(menuSecurity);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(32, 32, 32)
                        .addComponent(btnEdit)
                        .addGap(28, 28, 28)
                        .addComponent(btnFilter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSchedule)
                            .addComponent(lblName)
                            .addComponent(lblSpeciality)
                            .addComponent(lblClassName))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboSpeciality, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdOdd)
                            .addComponent(rdEv)
                            .addComponent(txtClassName)
                            .addComponent(txtLecturerName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpeciality)
                            .addComponent(cboSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClassName)
                            .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSchedule)
                            .addComponent(rdEv))
                        .addGap(27, 27, 27)
                        .addComponent(rdOdd)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnFilter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPreferenceActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void rdOddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdOddActionPerformed

    private void rdEvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdEvActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String lecturerName = txtLecturerName.getText();
        String className = txtClassName.getText();
        String speciality = (String) cboSpeciality.getSelectedItem();
        String schedule ="";
        if (rdEv.isSelected()){
            schedule = rdEv.getText();
        }
        else if (rdOdd.isSelected()){
            schedule = rdOdd.getText();
        }
        Clazz clazzNew = new Clazz(className, this.workplace, speciality, schedule, lecturerName);
        clazzes.add(clazzNew);
        System.out.println(clazzes);
        displayJTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void menuSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSecurityActionPerformed

    private void cboSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSpecialityActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            int row = jTable1.getSelectedRow();
            txtLecturerName.setText(clazzes.get(row).getLecturerName());
            if (clazzes.get(row).getSpeciality().equals(SpecialityConstant.WEBFRONTEND.value)){
                cboSpeciality.setSelectedIndex(1);
            } else if (clazzes.get(row).getSpeciality().equals(SpecialityConstant.WEBBACKEND.value)){
                cboSpeciality.setSelectedIndex(0);
            } else if (clazzes.get(row).getSpeciality().equals(SpecialityConstant.DEVOPSAWS.value)){
                cboSpeciality.setSelectedIndex(2);
            } else if (clazzes.get(row).getSpeciality().equals(SpecialityConstant.MOBILE.value)){
                cboSpeciality.setSelectedIndex(3);
            } else if (clazzes.get(row).getSpeciality().equals(SpecialityConstant.STEM.value)){
                cboSpeciality.setSelectedIndex(4);
            }
            txtClassName.setText(clazzes.get(row).getName());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Clazz clazz = clazzes.get(row);
        clazz.setLecturerName(txtLecturerName.getText());
        clazzes.set(row, clazz);
        clazz.setName( txtClassName.getText());
        clazz.setSpeciality( (String) cboSpeciality.getSelectedItem());
        String schedule ="";
        if (rdEv.isSelected()){
            schedule = rdEv.getText();
        }
        else if (rdOdd.isSelected()){
            schedule = rdOdd.getText();
        }
        clazz.setSchedule(schedule);
        displayJTable();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClazzMangementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClazzMangementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClazzMangementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClazzMangementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClazzMangementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.ButtonGroup btnGroupSchedule;
    private javax.swing.JComboBox<String> cboSpeciality;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JMenuItem menuPreference;
    private javax.swing.JMenuItem menuSecurity;
    private javax.swing.JRadioButton rdEv;
    private javax.swing.JRadioButton rdOdd;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtLecturerName;
    // End of variables declaration//GEN-END:variables

    private void displayJTable() {
        String col[] = {"ID","Lecturer's Name","Speciality", "Class's Name", "Schedule"};
        DefaultTableModel tableModel = new DefaultTableModel(col,0);
        for(int i=0;i<clazzes.size();i++){
            Object[] obj={clazzes.get(i).getId(), clazzes.get(i).getLecturerName(), 
                clazzes.get(i).getSpeciality(), clazzes.get(i).getName(), 
                clazzes.get(i).getSchedule()};
            
            tableModel.addRow(obj);
        }
        jTable1.setModel(tableModel);
    }
}
