/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import entity.Admin;
import entity.Clazz;
import entity.Lecturer;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.Main;

/**
 *
 * @author Admin
 */
public class LecturerMangagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form LecturerMangagementFrame
     */
    private Admin admin;
    private String workplace;
    private ArrayList<Clazz> clazzes;
    
    public LecturerMangagementFrame(Admin admin, String workplace, ArrayList<Clazz> clazzes){
        initComponents();
        this.setLocationRelativeTo(null);
        this.admin = admin;
        this.workplace = workplace;
        this.clazzes = clazzes;
        for (Lecturer lecturer : Main.lecturers) {
            Vector vectorRow = new Vector();
            vectorRow.add(lecturer.getId());
            vectorRow.add(lecturer.getAge());
            vectorRow.add(lecturer.getEmail());
            vectorRow.add(lecturer.getPhoneNumb());
            vectorRow.add(lecturer.isIsAssigned());
        }
        spnAge.setValue(18);
        displayJTable(jTable1);
    }
    public LecturerMangagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaInvalidDialog = new javax.swing.JDialog();
        lblInvalidDialog = new javax.swing.JLabel();
        btnCloseInvalidDialog = new javax.swing.JButton();
        diaSuccessfullyAdded = new javax.swing.JDialog();
        lblSuccessfullyAddedDialog = new javax.swing.JLabel();
        btnCloseAddedDialog = new javax.swing.JButton();
        diaSuccessfullyEdited = new javax.swing.JDialog();
        lblSuccessfullyEditedDialog = new javax.swing.JLabel();
        btnCloseEditedDialog = new javax.swing.JButton();
        btnBackToClazzMangagementPage = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        spnAge = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        chkLecturerAgeLeftBlank = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSetting = new javax.swing.JMenu();
        menuSecurity = new javax.swing.JMenuItem();
        ckbmenuDarkMode = new javax.swing.JCheckBoxMenuItem();
        menuAbout = new javax.swing.JMenu();

        lblInvalidDialog.setText("INVALID INPUT, PLEASE TRY AGAIN !");

        btnCloseInvalidDialog.setText("Ok");
        btnCloseInvalidDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseInvalidDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaInvalidDialogLayout = new javax.swing.GroupLayout(diaInvalidDialog.getContentPane());
        diaInvalidDialog.getContentPane().setLayout(diaInvalidDialogLayout);
        diaInvalidDialogLayout.setHorizontalGroup(
            diaInvalidDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaInvalidDialogLayout.createSequentialGroup()
                .addGroup(diaInvalidDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaInvalidDialogLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblInvalidDialog))
                    .addGroup(diaInvalidDialogLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCloseInvalidDialog)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        diaInvalidDialogLayout.setVerticalGroup(
            diaInvalidDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaInvalidDialogLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblInvalidDialog)
                .addGap(72, 72, 72)
                .addComponent(btnCloseInvalidDialog)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        lblSuccessfullyAddedDialog.setText("Successfully Added !");

        btnCloseAddedDialog.setText("Ok");
        btnCloseAddedDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAddedDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaSuccessfullyAddedLayout = new javax.swing.GroupLayout(diaSuccessfullyAdded.getContentPane());
        diaSuccessfullyAdded.getContentPane().setLayout(diaSuccessfullyAddedLayout);
        diaSuccessfullyAddedLayout.setHorizontalGroup(
            diaSuccessfullyAddedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyAddedLayout.createSequentialGroup()
                .addGroup(diaSuccessfullyAddedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaSuccessfullyAddedLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCloseAddedDialog))
                    .addGroup(diaSuccessfullyAddedLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblSuccessfullyAddedDialog)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        diaSuccessfullyAddedLayout.setVerticalGroup(
            diaSuccessfullyAddedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyAddedLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblSuccessfullyAddedDialog)
                .addGap(65, 65, 65)
                .addComponent(btnCloseAddedDialog)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        lblSuccessfullyEditedDialog.setText("Successfully Edited !");

        btnCloseEditedDialog.setText("Ok");
        btnCloseEditedDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseEditedDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaSuccessfullyEditedLayout = new javax.swing.GroupLayout(diaSuccessfullyEdited.getContentPane());
        diaSuccessfullyEdited.getContentPane().setLayout(diaSuccessfullyEditedLayout);
        diaSuccessfullyEditedLayout.setHorizontalGroup(
            diaSuccessfullyEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyEditedLayout.createSequentialGroup()
                .addGroup(diaSuccessfullyEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaSuccessfullyEditedLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCloseEditedDialog))
                    .addGroup(diaSuccessfullyEditedLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblSuccessfullyEditedDialog)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        diaSuccessfullyEditedLayout.setVerticalGroup(
            diaSuccessfullyEditedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyEditedLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblSuccessfullyEditedDialog)
                .addGap(65, 65, 65)
                .addComponent(btnCloseEditedDialog)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBackToClazzMangagementPage.setText("Back to the Previous Page");
        btnBackToClazzMangagementPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToClazzMangagementPageActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblAge.setText("Age:");

        lblEmail.setText("Email:");

        lblPhoneNumber.setText("Phone Number:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Email", "Phone Number", "Assigned"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        chkLecturerAgeLeftBlank.setText("Left Blank");
        chkLecturerAgeLeftBlank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLecturerAgeLeftBlankActionPerformed(evt);
            }
        });

        menuSetting.setText("Setting");
        menuSetting.setToolTipText("");
        menuSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSettingActionPerformed(evt);
            }
        });

        menuSecurity.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSecurity.setText("Security");
        menuSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecurityActionPerformed(evt);
            }
        });
        menuSetting.add(menuSecurity);

        ckbmenuDarkMode.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ckbmenuDarkMode.setSelected(true);
        ckbmenuDarkMode.setText("Dark Mode");
        ckbmenuDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbmenuDarkModeActionPerformed(evt);
            }
        });
        menuSetting.add(ckbmenuDarkMode);

        jMenuBar1.add(menuSetting);

        menuAbout.setText("About");
        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBackToClazzMangagementPage))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAge)
                                .addComponent(lblName)
                                .addComponent(lblEmail)
                                .addComponent(lblPhoneNumber))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(spnAge)
                                    .addGap(18, 18, 18)
                                    .addComponent(chkLecturerAgeLeftBlank, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackToClazzMangagementPage)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAge)
                                .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkLecturerAgeLeftBlank)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecurityActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SecurityFrame(admin).setVisible(true);
    }//GEN-LAST:event_menuSecurityActionPerformed

    private void menuSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSettingActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String phoneNumb = txtPhoneNumber.getText();
        String email = txtEmail.getText();
        try {
            spnAge.commitEdit();
        } catch ( java.text.ParseException e ) { spnAge.setValue(18); }
        int age = (Integer) spnAge.getValue();
        if (chkLecturerAgeLeftBlank.isSelected()) {
            age = -1;
        }
        if ((name.equals("")||Main.validator.isValidName(name)) && (email.equals("")||Main.validator.isValidEmail(email)) && (phoneNumb.equals("")||Main.validator.isValidPhoneNumber(phoneNumb)) && (chkLecturerAgeLeftBlank.isSelected()||(age>=18&&age<=100))){
            Lecturer lecturer = new Lecturer(name, age, email, phoneNumb);
            Main.lecturers.add(lecturer);
            diaSuccessfullyAdded.pack();
            diaSuccessfullyAdded.setVisible(true);
            diaSuccessfullyAdded.getPreferredSize();
        } else {
            diaInvalidDialog.pack();
            diaInvalidDialog.setVisible(true);
            diaInvalidDialog.getPreferredSize();
        }
         
        displayJTable(jTable1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void ckbmenuDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbmenuDarkModeActionPerformed
        // TODO add your handling code here:
        if (ckbmenuDarkMode.isSelected()){
            this.getContentPane().setBackground(Color.black);
            lblAge.setForeground(Color.white);
            lblName.setForeground(Color.white);
            lblEmail.setForeground(Color.white);
            lblPhoneNumber.setForeground(Color.white);
        } else {
            this.getContentPane().setBackground(Color.white);
            lblAge.setForeground(Color.black);
            lblName.setForeground(Color.black);
            lblEmail.setForeground(Color.black);
            lblPhoneNumber.setForeground(Color.black);
        }
    }//GEN-LAST:event_ckbmenuDarkModeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1){
            Lecturer lecturerSelected = Main.lecturers.get(jTable1.getSelectedRow());
            txtEmail.setText(lecturerSelected.getEmail());
            txtName.setText(lecturerSelected.getName());
            txtPhoneNumber.setText(lecturerSelected.getPhoneNumb());
            spnAge.setValue(lecturerSelected.getAge());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            return;
        }
        Lecturer lecturerSelected = Main.lecturers.get(jTable1.getSelectedRow());
        try {
            spnAge.commitEdit();
        } catch ( java.text.ParseException e ) { spnAge.setValue(18); }
        int age = (Integer) spnAge.getValue();
        if (chkLecturerAgeLeftBlank.isSelected()) {
            age = -1;
        }
        lecturerSelected.setAge(age);
        String email = txtEmail.getText();
        String name = txtName.getText();
        String phoneNumb = txtPhoneNumber.getText();
        if ((name.equals("")||Main.validator.isValidName(name)) && (email.equals("")||Main.validator.isValidEmail(email)) && (phoneNumb.equals("")||Main.validator.isValidPhoneNumber(phoneNumb)) && (chkLecturerAgeLeftBlank.isSelected()||(age>=18&&age<=100))) {
            lecturerSelected.setEmail(email);
            lecturerSelected.setName(name);
            lecturerSelected.setPhoneNumb(phoneNumb);
            diaSuccessfullyEdited.pack();
            diaSuccessfullyEdited.setVisible(true);
            diaSuccessfullyEdited.getPreferredSize();
        } else {
            diaInvalidDialog.pack();
            diaInvalidDialog.setVisible(true);
            diaInvalidDialog.getPreferredSize();
        }
        displayJTable(jTable1);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackToClazzMangagementPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToClazzMangagementPageActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ClazzMangementFrame(admin, clazzes, workplace).setVisible(true);
    }//GEN-LAST:event_btnBackToClazzMangagementPageActionPerformed

    private void btnCloseInvalidDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseInvalidDialogActionPerformed
        // TODO add your handling code here:
        diaInvalidDialog.setVisible(false);
    }//GEN-LAST:event_btnCloseInvalidDialogActionPerformed

    private void chkLecturerAgeLeftBlankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLecturerAgeLeftBlankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLecturerAgeLeftBlankActionPerformed

    private void btnCloseAddedDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAddedDialogActionPerformed
        // TODO add your handling code here:
        diaSuccessfullyAdded.setVisible(false);
    }//GEN-LAST:event_btnCloseAddedDialogActionPerformed

    private void btnCloseEditedDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseEditedDialogActionPerformed
        // TODO add your handling code here:
        diaSuccessfullyEdited.setVisible(false);
    }//GEN-LAST:event_btnCloseEditedDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerMangagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerMangagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerMangagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerMangagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerMangagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackToClazzMangagementPage;
    private javax.swing.JButton btnCloseAddedDialog;
    private javax.swing.JButton btnCloseEditedDialog;
    private javax.swing.JButton btnCloseInvalidDialog;
    private javax.swing.JButton btnEdit;
    private javax.swing.JCheckBox chkLecturerAgeLeftBlank;
    private javax.swing.JCheckBoxMenuItem ckbmenuDarkMode;
    private javax.swing.JDialog diaInvalidDialog;
    private javax.swing.JDialog diaSuccessfullyAdded;
    private javax.swing.JDialog diaSuccessfullyEdited;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInvalidDialog;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSuccessfullyAddedDialog;
    private javax.swing.JLabel lblSuccessfullyEditedDialog;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuSecurity;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables

    private void displayJTable(JTable jTable) {
        String col[] = {"ID","Name","Age", "Email", "Phone Number", "Assigned"};
        DefaultTableModel tableModel = new DefaultTableModel(col,0);
        for(int i=0;i<Main.lecturers.size();i++){
            Object[] obj={Main.lecturers.get(i).getId(), Main.lecturers.get(i).getName(), 
                Main.lecturers.get(i).getAge(), Main.lecturers.get(i).getEmail(), 
                Main.lecturers.get(i).getPhoneNumb(), Main.lecturers.get(i).isIsAssigned()};
            
            tableModel.addRow(obj);
        }
        jTable.setModel(tableModel);
    }
}
