/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import entity.Admin;
import java.awt.Color;
import main.Main;

/**
 *
 * @author Admin
 */
public class SecurityFrame extends javax.swing.JFrame {

    /**
     * Creates new form SecurityFrame
     */
    private Admin admin;
    public SecurityFrame(Admin admin) {
        initComponents();
        this.getContentPane().setBackground(new Color(204, 204, 255));
        this.setLocationRelativeTo(null);
        this.admin = admin;
 
        txtName.setText(admin.getName());
        txtUsername.setText(admin.getUsername());
        txtEmail.setText(admin.getEmail());
        txtPhoneNumber.setText(admin.getPhoneNumb());
        spnAge.setValue(admin.getAge());
        txtPassword.setText(admin.getPassword());
    }
    public SecurityFrame() {
        initComponents();
        this.getContentPane().setBackground(new Color(204, 204, 255));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaInvalidInput = new javax.swing.JDialog();
        btnCloseDialog1 = new javax.swing.JButton();
        lblDialog1 = new javax.swing.JLabel();
        diaSuccessfullyUpdated = new javax.swing.JDialog();
        lblDialog2 = new javax.swing.JLabel();
        btnCloseDialog2 = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnBackToHomePage = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        spnAge = new javax.swing.JSpinner();

        diaInvalidInput.setTitle("\n\n\n\n\t\t                     INVALID VALUES DETECTED!\t\n\t\t\tPLEASE CHECK AGAIN!");

        btnCloseDialog1.setText("Ok");
        btnCloseDialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDialog1ActionPerformed(evt);
            }
        });

        lblDialog1.setText("INVALID INPUT DETECTED!");

        javax.swing.GroupLayout diaInvalidInputLayout = new javax.swing.GroupLayout(diaInvalidInput.getContentPane());
        diaInvalidInput.getContentPane().setLayout(diaInvalidInputLayout);
        diaInvalidInputLayout.setHorizontalGroup(
            diaInvalidInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaInvalidInputLayout.createSequentialGroup()
                .addGroup(diaInvalidInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaInvalidInputLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnCloseDialog1))
                    .addGroup(diaInvalidInputLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblDialog1)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        diaInvalidInputLayout.setVerticalGroup(
            diaInvalidInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaInvalidInputLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(lblDialog1)
                .addGap(101, 101, 101)
                .addComponent(btnCloseDialog1)
                .addGap(41, 41, 41))
        );

        lblDialog2.setText("Update Successfully!");

        btnCloseDialog2.setText("Ok");
        btnCloseDialog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDialog2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaSuccessfullyUpdatedLayout = new javax.swing.GroupLayout(diaSuccessfullyUpdated.getContentPane());
        diaSuccessfullyUpdated.getContentPane().setLayout(diaSuccessfullyUpdatedLayout);
        diaSuccessfullyUpdatedLayout.setHorizontalGroup(
            diaSuccessfullyUpdatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyUpdatedLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(diaSuccessfullyUpdatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaSuccessfullyUpdatedLayout.createSequentialGroup()
                        .addComponent(btnCloseDialog2)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaSuccessfullyUpdatedLayout.createSequentialGroup()
                        .addComponent(lblDialog2)
                        .addGap(128, 128, 128))))
        );
        diaSuccessfullyUpdatedLayout.setVerticalGroup(
            diaSuccessfullyUpdatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSuccessfullyUpdatedLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(lblDialog2)
                .addGap(92, 92, 92)
                .addComponent(btnCloseDialog2)
                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(102, 153, 255));
        lblUsername.setText("2, Username:");

        lblPassword.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 153, 255));
        lblPassword.setText("3, Password:");

        lblAge.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(102, 153, 255));
        lblAge.setText("4, Age:");

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 153, 255));
        lblEmail.setText("5, Email:");

        lblPhoneNumber.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(102, 153, 255));
        lblPhoneNumber.setText("6, Phone Number:");

        lblName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 153, 255));
        lblName.setText("1, Name:");

        btnBackToHomePage.setBackground(new java.awt.Color(102, 102, 255));
        btnBackToHomePage.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBackToHomePage.setForeground(new java.awt.Color(255, 204, 255));
        btnBackToHomePage.setText("Back to Home Page");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdate.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 204, 255));
        btnUpdate.setText("Confirm Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        spnAge.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBackToHomePage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPhoneNumber)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnUpdate)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAge)
                                    .addGap(390, 390, 390))))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBackToHomePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnUpdate)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String name = txtUsername.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String email = txtEmail.getText();
        String phoneNumb = txtPhoneNumber.getText();
        try {
            spnAge.commitEdit();
        } catch ( java.text.ParseException e ) { spnAge.setValue(0); }
        int age = (Integer) spnAge.getValue();
        if (Main.validator.isValidEmail(email) && Main.validator.isValidName(name) && Main.validator.isValidPassword(password) && Main.validator.isValidPhoneNumber(phoneNumb) && age>=18 && age <=100){
           admin.setAge(age);
           admin.setEmail(email);
           admin.setName(name);
           admin.setPassword(password);
           admin.setPhoneNumb(phoneNumb);
           admin.setUsername(username);
           diaSuccessfullyUpdated.pack();
           diaSuccessfullyUpdated.setVisible(true);
           diaSuccessfullyUpdated.getPreferredSize();
        } else {
           diaInvalidInput.pack();
           diaInvalidInput.setVisible(true);
           diaInvalidInput.getPreferredSize();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCloseDialog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDialog2ActionPerformed
        // TODO add your handling code here:\
        diaSuccessfullyUpdated.setVisible(false);
    }//GEN-LAST:event_btnCloseDialog2ActionPerformed

    private void btnCloseDialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDialog1ActionPerformed
        // TODO add your handling code here:
        diaInvalidInput.setVisible(false);
    }//GEN-LAST:event_btnCloseDialog1ActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        // TODO add your handling code here:\
        this.setVisible(false);
        new HomeFrame(admin).setVisible(true);
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecurityFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnCloseDialog1;
    private javax.swing.JButton btnCloseDialog2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDialog diaInvalidInput;
    private javax.swing.JDialog diaSuccessfullyUpdated;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDialog1;
    private javax.swing.JLabel lblDialog2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
